/** @typedef {{ id: string, number: number, name: string, category: string, wing: string, tagline: string, description: string, path: string, eip?: string, palette: string[] }} ErcWork */

/** @type {ErcWork[]} */
export const CATALOG = [
  {
    id: "erc1363",
    number: 1363,
    name: "Payable Token",
    category: "Token salon",
    wing: "token",
    tagline: "Transfer with intent",
    description:
      "ERC-20 extension that calls recipients and spenders on transfer and approval—enabling composable payment flows without separate hooks.",
    path: "token/ERC1363",
    eip: "https://eips.ethereum.org/EIPS/eip-1363",
    palette: ["#f4e4c8", "#c9a66b", "#8b5e34", "#2d1810"],
  },
  {
    id: "erc5192",
    number: 5192,
    name: "Minimal Soulbound NFT",
    category: "Token salon",
    wing: "token",
    tagline: "Bound to identity",
    description:
      "Non-transferable ERC-721 tokens with an explicit locked state—credentials and attestations that cannot walk off the wall.",
    path: "token/ERC5192",
    eip: "https://eips.ethereum.org/EIPS/eip-5192",
    palette: ["#e8e0f0", "#9b8ab8", "#5c4d72", "#1a1228"],
  },
  {
    id: "erc4907",
    number: 4907,
    name: "Rental NFT",
    category: "Token salon",
    wing: "token",
    tagline: "Temporary custody",
    description:
      "Splits owner and user roles with expiring utility—time-limited access for rentals, subscriptions, and delegated use.",
    path: "token/ERC4907",
    eip: "https://eips.ethereum.org/EIPS/eip-4907",
    palette: ["#dff3f0", "#6bb8a8", "#2d6b5e", "#0f2e28"],
  },
  {
    id: "erc4906",
    number: 4906,
    name: "Metadata Update",
    category: "Token salon",
    wing: "token",
    tagline: "Living portraits",
    description:
      "Signals when token metadata changes so indexers and marketplaces refresh the frame without guesswork.",
    path: "token/ERC4906",
    eip: "https://eips.ethereum.org/EIPS/eip-4906",
    palette: ["#fff5e6", "#e8b86d", "#b87a2b", "#4a3018"],
  },
  {
    id: "erc5484",
    number: 5484,
    name: "Consensual Soulbound",
    category: "Token salon",
    wing: "token",
    tagline: "Burn by agreement",
    description:
      "Soulbound tokens with per-token burn authorization—revocable credentials when both parties consent.",
    path: "token/ERC5484",
    eip: "https://eips.ethereum.org/EIPS/eip-5484",
    palette: ["#f0e6f6", "#c77dba", "#7a3d6e", "#2a1024"],
  },
  {
    id: "erc2309",
    number: 2309,
    name: "Consecutive Transfer",
    category: "Token salon",
    wing: "token",
    tagline: "Serial minting",
    description: "Batch minting via consecutive token IDs—gas-efficient genesis for large collections.",
    path: "token/ERC2309",
    eip: "https://eips.ethereum.org/EIPS/eip-2309",
    palette: ["#e6f0ff", "#6b9fd4", "#2d4a6b", "#0f1a2e"],
  },
  {
    id: "erc3525",
    number: 3525,
    name: "Semi-Fungible Token",
    category: "Token salon",
    wing: "token",
    tagline: "Slot and value",
    description:
      "ERC-721 compatible SFT with a slot model—financial instruments and bundled positions as first-class objects.",
    path: "token/ERC3525",
    eip: "https://eips.ethereum.org/EIPS/eip-3525",
    palette: ["#f8f0e8", "#d4a574", "#8c5c38", "#3d2418"],
  },
  {
    id: "erc7818",
    number: 7818,
    name: "Expirable ERC-20",
    category: "Token salon",
    wing: "token",
    tagline: "Time-bound balances",
    description:
      "Epoch-based ERC-20 where minted buckets expire—balanceOf excludes stale epochs, FIFO spend across valid ones, time or block clocks.",
    path: "token/ERC7818",
    eip: "https://eips.ethereum.org/EIPS/eip-7818",
    palette: ["#fde8e8", "#e07070", "#9a3030", "#3d1010"],
  },
  {
    id: "erc1271",
    number: 1271,
    name: "Signature Validation",
    category: "Cryptography wing",
    wing: "crypto",
    tagline: "Contracts that sign",
    description:
      "Standard interface for smart contract wallets to validate signatures—enabling multisig and account abstraction flows.",
    path: "utils/cryptography/ERC1271",
    eip: "https://eips.ethereum.org/EIPS/eip-1271",
    palette: ["#eef2ff", "#7b8fd4", "#3d4a7a", "#151a2e"],
  },
  {
    id: "erc6492",
    number: 6492,
    name: "Predeploy Validation",
    category: "Cryptography wing",
    wing: "crypto",
    tagline: "Before deployment",
    description:
      "Universal validator for counterfactual and predeploy wallet signatures—one library for EOAs and not-yet-deployed accounts.",
    path: "utils/cryptography/ERC6492",
    eip: "https://eips.ethereum.org/EIPS/eip-6492",
    palette: ["#f5f5f0", "#a8a89e", "#5c5c54", "#1a1a18"],
  },
  {
    id: "erc2771",
    number: 2771,
    name: "Meta Transactions",
    category: "Infrastructure hall",
    wing: "infra",
    tagline: "Gasless context",
    description: "Trusted forwarder context for relayed transactions—users sign, relayers deliver.",
    path: "metatx/ERC2771Context",
    eip: "https://eips.ethereum.org/EIPS/eip-2771",
    palette: ["#e8f4fc", "#5ba8d4", "#2a5f7a", "#0d2230"],
  },
  {
    id: "erc3156",
    number: 3156,
    name: "Flash Loans",
    category: "DeFi gallery",
    wing: "defi",
    tagline: "Instant liquidity",
    description:
      "Generic flash lender interface for uncollateralized single-block loans—DeFi's brief, brilliant loan.",
    path: "finance/ERC3156FlashLender",
    eip: "https://eips.ethereum.org/EIPS/eip-3156",
    palette: ["#fff8e8", "#e8c84a", "#9a7b18", "#3d3010"],
  },
  {
    id: "erc7201",
    number: 7201,
    name: "Namespaced Storage",
    category: "Infrastructure hall",
    wing: "infra",
    tagline: "Collision-free slots",
    description:
      "ERC-7201 storage slot derivation for upgradeable contracts—namespaces that never overwrite each other.",
    path: "utils/StorageSlot7201",
    eip: "https://eips.ethereum.org/EIPS/eip-7201",
    palette: ["#f0f4f8", "#94a3b8", "#475569", "#1e293b"],
  },
  {
    id: "erc2535",
    number: 2535,
    name: "Diamonds",
    category: "Infrastructure hall",
    wing: "infra",
    tagline: "Multi-facet proxy",
    description:
      "Modular proxy with multiple implementation facets—upgradeable systems as curated installations.",
    path: "diamond/Diamond",
    eip: "https://eips.ethereum.org/EIPS/eip-2535",
    palette: ["#f8f4ff", "#a78bfa", "#6d28d9", "#2e1065"],
  },
  {
    id: "erc4361",
    number: 4361,
    name: "Sign-In with Ethereum",
    category: "Auth atrium",
    wing: "agent",
    tagline: "On-chain login",
    description:
      "SIWE library, structured parser, and verifier for ERC-191 message authentication—wallet sign-in as gallery admission.",
    path: "auth/SIWE",
    eip: "https://eips.ethereum.org/EIPS/eip-4361",
    palette: ["#fef3e8", "#e07a4a", "#9a3d28", "#3d1810"],
  },
  {
    id: "erc8004",
    number: 8004,
    name: "Trustless Agents",
    category: "Agents pavilion",
    wing: "agent",
    tagline: "Identity & reputation",
    description:
      "Three registries for AI agents: ERC-721 identity, on-chain reputation feedback, and validation hooks—trust for the agentic economy.",
    path: "agent/ERC8004IdentityRegistry",
    eip: "https://eips.ethereum.org/EIPS/eip-8004",
    palette: ["#e8faf4", "#34d399", "#047857", "#064e3b"],
  },
];

export const WINGS = {
  all: "All wings",
  token: "Token salon",
  crypto: "Cryptography wing",
  defi: "DeFi gallery",
  infra: "Infrastructure hall",
  agent: "Agents pavilion",
};
